### ISSUE TITLE
Build fails to find installed ftxui

### ISSUE THREAD

**Issue by yurivict** [ArthurSonzogni/git-tui#14]
It only tries to fetch it [here](https://github.com/ArthurSonzogni/git-tui/blob/master/CMakeLists.txt#L8) for some reason.

I think the same is true for other projects using ftxui.

**Comment by ArthurSonzogni** [comment]
Hello,

It seems to work. See:

https://user-images.githubusercontent.com/4759106/211579783-e0905da9-1af4-420b-9d91-e7093c993852.mp4

Could you provide some instructions about how to reproduce the issue?

**Comment by yurivict** [comment]
The FreeBSD framework adds ```-DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON``` to cmake args - this causes this failure.

But downloads aren't allowed during package build. Is there a reason that fetch is used instead of a simple ```find_package(ftxui)```? Does it depend on a particular version of ftxui?

**Comment by ArthurSonzogni** [comment]
Do you know why: `The FreeBSD framework adds -DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON`.
I guess you would like packages to come from the OS package manager, instead of using cmake as a package manager.

`git-tui` depends currently on b56afce48ccd472cd2c3a53e619de0db1e7227a4, which is  5 patchs before HEAD, and 66 patch beyond the latest released.

I often develop `FTXUI` patches, to bring new improvement to `git-tui`, which make it unlikely to keep `git-tui` on past released versions. Ensuring this would either slow down git-tui development, or force FTXUI to release new version very often.

**Comment by ArthurSonzogni** [comment]
I tried building against an installed version of FTXUI, both the currently used one, and v3.0.0.
Both worked, despite the breaking changes. There are only a few fixed bug that would be sad to miss.

**Comment by yurivict** [comment]
> I guess you would like packages to come from the OS package manager, instead of using cmake as a package manager.

Downloads aren't allowed during package builds.

If you want to depend on some particular revision of ftxui git-submodule is the right way to do it.

**Comment by ArthurSonzogni** [comment]
@yurivict you can now use ftxui from the package installed on the system.

Same for the subprocess library, but I guess it isn't installable.
